plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.services)
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

android {
    namespace 'com.example.homeserviceapp'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.homeserviceapp"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        
        // Inject Cloudinary keys from local.properties
        buildConfigField "String", "CLOUDINARY_CLOUD_NAME", "\"" + (localProperties['cloudinary.cloud_name'] ?: "") + "\""
        buildConfigField "String", "CLOUDINARY_API_KEY", "\"" + (localProperties['cloudinary.api_key'] ?: "") + "\""
        buildConfigField "String", "CLOUDINARY_API_SECRET", "\"" + (localProperties['cloudinary.api_secret'] ?: "") + "\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
        buildConfig = true
    }
}

dependencies {

    // AndroidX
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.annotation
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // UI
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.viewpager2:viewpager2:1.0.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'io.github.chaosleung:pinview:1.4.4'

    // Firebase BoM
    implementation platform('com.google.firebase:firebase-bom:32.7.0')

    // Firebase services
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'com.google.firebase:firebase-database'

    // Glide
    implementation 'com.github.bumptech.glide:glide:4.16.0'

    implementation 'com.cloudinary:cloudinary-android:2.5.0'

    implementation 'com.google.firebase:firebase-messaging'

}
